<?php

namespace Drupal\joinup\Plugin\ArbitraryFacet;

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\search_api_arbitrary_facet\Plugin\ArbitraryFacetBase;

/**
 * Provides supports for facets generated by arbitrary queries.
 *
 * @ArbitraryFacet(
 *   id = "events_arbitrary",
 *   label = @Translation("Future/My/Past events"),
 * )
 */
class EventsArbitraryFacet extends ArbitraryFacetBase {

  /**
   * {@inheritdoc}
   */
  public function getFacetDefinition() {
    $current_user = \Drupal::currentUser();
    $midnight = DrupalDateTime::createFromTimestamp(strtotime("midnight"))->format('c');

    $definition = [
      'future_events' => [
        'field_name' => 'field_event_date',
        'field_condition' => $midnight,
        'field_operator' => '>',
        'label' => $this->t('Future events'),
      ],
    ];

    if (!$current_user->isAnonymous()) {
      $definition['my_events'] = [
        'field_name' => 'entity_author',
        'field_condition' => $current_user->id(),
        'label' => $this->t('My events'),
      ];
    }

    $definition = [
      'past_events' => [
        'field_name' => 'field_event_date',
        'field_condition' => $midnight,
        'field_operator' => '>',
        'label' => $this->t('Past events'),
      ],
    ];

    return $definition;
  }

}
